// ═══════════════════════════════════════════════════════════════════
// Docker Compose Template
// ═══════════════════════════════════════════════════════════════════

import type { DockerComposeConfig } from '../types.js';

export function generateDockerCompose(config: DockerComposeConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    replicas = 3,
    cpuLimit = '0.5',
    memoryLimit = '512M',
    includeMongo = true,
    includeRedis = true,
    envVars = {}
  } = config;

  const envLines = Object.entries(envVars)
    .map(([k, v]) => `      - ${k}=${v}`)
    .join('\n');

  // Use replica set connection string for transaction support
  const mongoEnv = includeMongo ? `      - MONGO_URI=mongodb://mongo:27017/${name.replace(/-/g, '_')}?replicaSet=rs0&directConnection=true` : '';
  const redisEnv = includeRedis ? `      - REDIS_URL=redis://redis:6379` : '';

  const dependsOn = [];
  if (includeMongo) dependsOn.push('mongo:\n        condition: service_healthy');
  if (includeRedis) dependsOn.push('redis:\n        condition: service_healthy');
  const dependsOnSection = dependsOn.length > 0 
    ? `    depends_on:\n      ${dependsOn.join('\n      ')}`
    : '';

  let yaml = `# ═══════════════════════════════════════════════════════════════════
# Docker Compose - Development & Production
# Generated by service-core infra generator
# ═══════════════════════════════════════════════════════════════════

version: '3.8'

services:
  # ─────────────────────────────────────────────────────────────────
  # ${name} (scalable)
  # ─────────────────────────────────────────────────────────────────
  ${name}:
    build: .
    ports:
      - "${port}:${port}"
    environment:
      - NODE_ENV=production
      - PORT=${port}
${mongoEnv}
${redisEnv}
      - JWT_SECRET=\${JWT_SECRET:-your-256-bit-secret-change-me}
${envLines}
${dependsOnSection}
    restart: unless-stopped
    deploy:
      replicas: ${replicas}
      resources:
        limits:
          cpus: '${cpuLimit}'
          memory: ${memoryLimit}
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${port}${healthPath}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ─────────────────────────────────────────────────────────────────
  # Load Balancer (Nginx)
  # ─────────────────────────────────────────────────────────────────
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - ${name}
    restart: unless-stopped
`;

  if (includeMongo) {
    yaml += generateMongoService();
  }

  if (includeRedis) {
    yaml += generateRedisService();
  }

  yaml += `
volumes:`;
  if (includeMongo) yaml += `\n  mongo_data:`;
  if (includeRedis) yaml += `\n  redis_data:`;
  yaml += '\n';

  return yaml;
}

/**
 * Generate MongoDB service with replica set support for transactions
 */
function generateMongoService(): string {
  return `
  # ─────────────────────────────────────────────────────────────────
  # MongoDB (Replica Set for transaction support)
  # ─────────────────────────────────────────────────────────────────
  mongo:
    image: mongo:7
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: |
        mongosh --eval "
          try {
            rs.status().ok
          } catch (e) {
            rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongo:27017'}]});
            1
          }
        " | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped
`;
}

/**
 * Generate Redis service for caching and pub/sub
 */
function generateRedisService(): string {
  return `
  # ─────────────────────────────────────────────────────────────────
  # Redis (for pub/sub & caching)
  # ─────────────────────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
`;
}

