// ═══════════════════════════════════════════════════════════════════
// Docker Image (Dockerfile) Template
// ═══════════════════════════════════════════════════════════════════

import type { DockerConfig } from '../types.js';

export function generateDockerfile(config: DockerConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    nodeVersion = '20',
    entryPoint = 'dist/index.js',
    serviceCorePackageName = 'core-service',
    coreServiceFolderName = 'core-service',
  } = config;
  
  // Convert service name to folder name (e.g., 'retail-api' stays 'retail-api')
  const appFolder = name;

  return `# ═══════════════════════════════════════════════════════════════════
# Multi-stage build for minimal image size
# Generated by core-service infra generator
# 
# BUILD FROM PARENT DIRECTORY:
#   docker build -f ${appFolder}/Dockerfile -t ${name} .
# ═══════════════════════════════════════════════════════════════════

# Stage 1: Build access-engine (core-service dependency)
FROM node:${nodeVersion}-alpine AS access-engine-builder
WORKDIR /build/access-engine
COPY access-engine/package*.json ./
RUN npm ci
COPY access-engine/src ./src
COPY access-engine/tsconfig.json ./
RUN npm run build

# Stage 2: Build shared-validators
FROM node:${nodeVersion}-alpine AS shared-validators-builder
WORKDIR /build/shared-validators
COPY shared-validators/package*.json ./
RUN npm ci
COPY shared-validators/src ./src
COPY shared-validators/tsconfig.json ./
RUN npm run build

# Stage 3: Build core-service
FROM node:${nodeVersion}-alpine AS core-service-builder
WORKDIR /build

# Copy built dependencies
COPY --from=access-engine-builder /build/access-engine /build/access-engine

# Build core-service
WORKDIR /build/${coreServiceFolderName}
COPY ${coreServiceFolderName}/package*.json ./
RUN npm ci --ignore-scripts
COPY ${coreServiceFolderName}/src ./src
COPY ${coreServiceFolderName}/tsconfig.json ./
RUN npm run build

# Stage 4: Build app
FROM node:${nodeVersion}-alpine AS app-builder
WORKDIR /app

# Install build tools for native modules (bcrypt, etc)
RUN apk add --no-cache python3 make g++

# Copy built packages
COPY --from=access-engine-builder /build/access-engine /access-engine
COPY --from=shared-validators-builder /build/shared-validators /shared-validators
COPY --from=core-service-builder /build/${coreServiceFolderName} /${coreServiceFolderName}

# Copy app package files and install
COPY ${appFolder}/package*.json ./
RUN npm ci --ignore-scripts

# Install TypeScript for build
RUN npm install -D typescript

# Copy source and build
COPY ${appFolder}/src ./src
COPY ${appFolder}/tsconfig.json ./
RUN npx tsc

# Stage 5: Production
FROM node:${nodeVersion}-alpine AS production
WORKDIR /app

# Security: non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001
USER nodejs

# Copy built files
COPY --from=app-builder --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --from=app-builder --chown=nodejs:nodejs /app/dist ./dist
COPY --from=app-builder --chown=nodejs:nodejs /app/package.json ./

# Copy local packages to node_modules
COPY --from=access-engine-builder --chown=nodejs:nodejs /build/access-engine /app/node_modules/access-engine
COPY --from=shared-validators-builder --chown=nodejs:nodejs /build/shared-validators /app/node_modules/shared-validators
COPY --from=core-service-builder --chown=nodejs:nodejs /build/${coreServiceFolderName} /app/node_modules/${serviceCorePackageName}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${port}${healthPath} || exit 1

# Environment
ENV NODE_ENV=production
ENV PORT=${port}

EXPOSE ${port}

CMD ["node", "${entryPoint}"]
`;
}

