// ═══════════════════════════════════════════════════════════════════
// Docker Compose Template
// ═══════════════════════════════════════════════════════════════════

import type { DockerComposeConfig } from '../types.js';

export function generateDockerCompose(config: DockerComposeConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    replicas = 3,
    cpuLimit = '0.5',
    memoryLimit = '512M',
    includeMongo = true,
    includeRedis = true,
    namespace = process.env.DOCKER_NAMESPACE || process.env.MS_NAMESPACE || 'ms',
    mongoContainerName = process.env.MONGO_CONTAINER_NAME || `${namespace}-mongo`,
    redisContainerName = process.env.REDIS_CONTAINER_NAME || `${namespace}-redis`,
    mongoImageVersion = process.env.MONGO_IMAGE_VERSION || 'latest',
    redisImageVersion = process.env.REDIS_IMAGE_VERSION || 'latest',
    mongoPort = parseInt(process.env.MONGO_PORT || '27017', 10),
    redisPort = parseInt(process.env.REDIS_PORT || '6379', 10),
    envVars = {}
  } = config;

  const envLines = Object.entries(envVars)
    .map(([k, v]) => `      - ${k}=${v}`)
    .join('\n');

  // Use configurable container names and ports
  const mongoEnv = includeMongo ? `      - MONGO_URI=mongodb://${mongoContainerName}:${mongoPort}/${name.replace(/-/g, '_')}?replicaSet=rs0&directConnection=true` : '';
  // Include Redis password in environment for services running inside Docker
  const redisPassword = process.env.REDIS_PASSWORD || 'redis123';
  const redisEnv = includeRedis ? `      - REDIS_URL=redis://${redisContainerName}:${redisPort}\n      - REDIS_PASSWORD=${redisPassword}` : '';

  const dependsOn = [];
  if (includeMongo) dependsOn.push(`${mongoContainerName}:\n        condition: service_healthy`);
  if (includeRedis) dependsOn.push(`${redisContainerName}:\n        condition: service_healthy`);
  const dependsOnSection = dependsOn.length > 0 
    ? `    depends_on:\n      ${dependsOn.join('\n      ')}`
    : '';

  let yaml = `# ═══════════════════════════════════════════════════════════════════
# Docker Compose - Development & Production
# Generated by service-core infra generator
# Namespace: ${namespace} (containers grouped under this namespace in Docker Desktop)
# ═══════════════════════════════════════════════════════════════════

name: ${namespace}

version: '3.8'

services:
  # ─────────────────────────────────────────────────────────────────
  # ${name} (scalable)
  # ─────────────────────────────────────────────────────────────────
  ${name}:
    build: .
    ports:
      - "${port}:${port}"
    environment:
      - NODE_ENV=production
      - PORT=${port}
${mongoEnv}
${redisEnv}
      - JWT_SECRET=\${JWT_SECRET:-your-256-bit-secret-change-me}
${envLines}
${dependsOnSection}
    labels:
      - "com.docker.compose.project=${namespace}"
      - "com.microservices.namespace=${namespace}"
      - "com.microservices.service=${name}"
      - "com.microservices.type=application"
    restart: unless-stopped
    deploy:
      replicas: ${replicas}
      resources:
        limits:
          cpus: '${cpuLimit}'
          memory: ${memoryLimit}
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:${port}${healthPath}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ─────────────────────────────────────────────────────────────────
  # Load Balancer (Nginx)
  # ─────────────────────────────────────────────────────────────────
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - ${name}
    restart: unless-stopped
`;

  if (includeMongo) {
    yaml += generateMongoService(mongoContainerName, mongoImageVersion, mongoPort, namespace);
  }

  if (includeRedis) {
    yaml += generateRedisService(redisContainerName, redisImageVersion, redisPort, namespace);
  }

  yaml += `
networks:
  microservices-network:
    driver: bridge

volumes:`;
  if (includeMongo) {
    yaml += `\n  mongo_data:`;
    yaml += `\n  mongo_config:`;
  }
  if (includeRedis) yaml += `\n  redis_data:`;
  yaml += '\n';

  return yaml;
}

/**
 * Generate MongoDB service with replica set support for transactions
 */
function generateMongoService(
  containerName: string = 'ms-mongo',
  imageVersion: string = 'latest',
  port: number = 27017,
  namespace: string = 'ms'
): string {
  // Note: For single-node replica sets in development, we don't enable auth
  // as it requires keyFile. For production with multi-node, enable auth properly.
  return `
  # ─────────────────────────────────────────────────────────────────
  # MongoDB (Replica Set for transaction support)
  # ─────────────────────────────────────────────────────────────────
  ${containerName}:
    container_name: ${containerName}
    image: mongo:${imageVersion}
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "${port}:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - microservices-network
    labels:
      - "com.docker.compose.project=${namespace}"
      - "com.microservices.namespace=${namespace}"
      - "com.microservices.service=mongodb"
      - "com.microservices.type=infrastructure"
    healthcheck:
      test: |
        mongosh --quiet --eval "
          try {
            rs.status().ok
          } catch (e) {
            rs.initiate({_id: 'rs0', members: [{_id: 0, host: '${containerName}:27017'}]});
            1
          }
        " | grep -q 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: unless-stopped
`;
}

/**
 * Generate Redis service for caching and pub/sub
 */
function generateRedisService(
  containerName: string = 'ms-redis',
  imageVersion: string = 'latest',
  port: number = 6379,
  namespace: string = 'ms'
): string {
  return `
  # ─────────────────────────────────────────────────────────────────
  # Redis (for pub/sub & caching)
  # ─────────────────────────────────────────────────────────────────
  ${containerName}:
    container_name: ${containerName}
    image: redis:${imageVersion}
    ports:
      - "${port}:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "\${REDIS_PASSWORD:-redis123}"]
    networks:
      - microservices-network
    labels:
      - "com.docker.compose.project=${namespace}"
      - "com.microservices.namespace=${namespace}"
      - "com.microservices.service=redis"
      - "com.microservices.type=infrastructure"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
`;
}

