// ═══════════════════════════════════════════════════════════════════
// Docker Image (Dockerfile) Template
// Dynamically generates stages based on local dependencies
// ═══════════════════════════════════════════════════════════════════

import type { DockerConfig, LocalDependency } from '../types.js';

/**
 * Generate a Docker build stage for a local dependency
 */
function generateDependencyStage(
  dep: LocalDependency, 
  nodeVersion: string, 
  allDeps: LocalDependency[]
): string {
  const stageName = `${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder`;
  
  // Find dependencies that need to be copied in
  const copyFromStages = (dep.dependsOn || [])
    .map(depName => {
      const parentDep = allDeps.find(d => d.name === depName);
      if (!parentDep) return '';
      const parentStageName = `${parentDep.name.replace(/[^a-z0-9]/gi, '-')}-builder`;
      return `COPY --from=${parentStageName} /build/${parentDep.folderPath} /build/${parentDep.folderPath}`;
    })
    .filter(Boolean)
    .join('\n');
  
  const copyFromBlock = copyFromStages ? `\n# Copy dependencies\n${copyFromStages}\n` : '';
  
  return `# Build ${dep.name}
FROM node:\${nodeVersion}-alpine AS ${stageName}
WORKDIR /build/${dep.folderPath}
${copyFromBlock}
COPY ${dep.folderPath}/package*.json ./
RUN npm ci --ignore-scripts
COPY ${dep.folderPath}/src ./src
COPY ${dep.folderPath}/tsconfig.json ./
RUN npm run build`;
}

/**
 * Sort dependencies by their dependency order (dependencies first)
 */
function sortDependencies(deps: LocalDependency[]): LocalDependency[] {
  const sorted: LocalDependency[] = [];
  const visited = new Set<string>();
  
  function visit(dep: LocalDependency) {
    if (visited.has(dep.name)) return;
    
    // Visit dependencies first
    for (const depName of dep.dependsOn || []) {
      const parentDep = deps.find(d => d.name === depName);
      if (parentDep) visit(parentDep);
    }
    
    visited.add(dep.name);
    sorted.push(dep);
  }
  
  deps.forEach(visit);
  return sorted;
}

export function generateDockerfile(config: DockerConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    nodeVersion = '20',
    entryPoint = 'dist/index.js',
    localDependencies = [],
  } = config;
  
  const appFolder = name;
  
  // Sort dependencies so dependencies are built before dependents
  const sortedDeps = sortDependencies(localDependencies);
  
  // Generate build stages for each local dependency
  const dependencyStages = sortedDeps.map((dep, idx) => 
    `# Stage ${idx + 1}: Build ${dep.name}
FROM node:${nodeVersion}-alpine AS ${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder
WORKDIR /build/${dep.folderPath}
${(dep.dependsOn || []).map(depName => {
  const parentDep = sortedDeps.find(d => d.name === depName);
  if (!parentDep) return '';
  return `COPY --from=${parentDep.name.replace(/[^a-z0-9]/gi, '-')}-builder /build/${parentDep.folderPath} /build/${parentDep.folderPath}`;
}).filter(Boolean).join('\n')}
COPY ${dep.folderPath}/package*.json ./
RUN npm ci --ignore-scripts
COPY ${dep.folderPath}/src ./src
COPY ${dep.folderPath}/tsconfig.json ./
RUN npm run build`
  ).join('\n\n');
  
  // Generate COPY commands for app-builder stage
  const copyBuiltPackages = sortedDeps.map(dep => 
    `COPY --from=${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder /build/${dep.folderPath} /${dep.folderPath}`
  ).join('\n');
  
  // Generate COPY commands for production stage
  // Copy to node_modules for direct imports (with correct ownership)
  const copyToNodeModules = sortedDeps.map(dep => 
    `COPY --chown=nodejs:nodejs --from=${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder /build/${dep.folderPath} /app/node_modules/${dep.name}`
  ).join('\n');
  
  // Generate command to remove symlinks created by npm for file: dependencies
  const removeSymlinks = sortedDeps.map(dep => 
    `/app/node_modules/${dep.name}`
  ).join(' ');
  
  const appBuilderStageNum = sortedDeps.length + 1;
  const productionStageNum = sortedDeps.length + 2;

  // Handle case with no local dependencies
  if (sortedDeps.length === 0) {
    return `# ═══════════════════════════════════════════════════════════════════
# Multi-stage build for minimal image size
# Generated by core-service infra generator
# 
# BUILD FROM PARENT DIRECTORY:
#   docker build -f ${appFolder}/Dockerfile -t ${name} .
# ═══════════════════════════════════════════════════════════════════

# Stage 1: Build app
FROM node:${nodeVersion}-alpine AS app-builder
WORKDIR /app

# Copy app package files and install
COPY ${appFolder}/package*.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY ${appFolder}/src ./src
COPY ${appFolder}/tsconfig.json ./
RUN npx tsc

# Stage 2: Production
FROM node:${nodeVersion}-alpine AS production
WORKDIR /app

# Security: non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001
USER nodejs

# Copy built files
COPY --from=app-builder --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --from=app-builder --chown=nodejs:nodejs /app/dist ./dist
COPY --from=app-builder --chown=nodejs:nodejs /app/package.json ./

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${port}${healthPath} || exit 1

# Environment
ENV NODE_ENV=production
ENV PORT=${port}

EXPOSE ${port}

CMD ["node", "${entryPoint}"]
`;
  }

  return `# ═══════════════════════════════════════════════════════════════════
# Multi-stage build for minimal image size
# Generated by core-service infra generator
# 
# BUILD FROM PARENT DIRECTORY:
#   docker build -f ${appFolder}/Dockerfile -t ${name} .
# 
# Local dependencies: ${sortedDeps.map(d => d.name).join(', ')}
# ═══════════════════════════════════════════════════════════════════

${dependencyStages}

# Stage ${appBuilderStageNum}: Build app
FROM node:${nodeVersion}-alpine AS app-builder
WORKDIR /app

# Copy built local packages
${copyBuiltPackages}

# Copy app package files and install
COPY ${appFolder}/package*.json ./
RUN npm ci --ignore-scripts

# Install TypeScript for build
RUN npm install -D typescript

# Copy source and build
COPY ${appFolder}/src ./src
COPY ${appFolder}/tsconfig.json ./
RUN npx tsc

# Stage ${productionStageNum}: Production
FROM node:${nodeVersion}-alpine AS production
WORKDIR /app

# Security: create non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001

# Copy built files with correct ownership (no slow chown needed)
COPY --chown=nodejs:nodejs --from=app-builder /app/node_modules ./node_modules
COPY --chown=nodejs:nodejs --from=app-builder /app/dist ./dist
COPY --chown=nodejs:nodejs --from=app-builder /app/package.json ./

# Remove symlinks created by npm for file: dependencies (they point to build-time paths)
RUN rm -f ${removeSymlinks}

# Copy local packages to node_modules (replacing the removed symlinks)
${copyToNodeModules}

# Switch to non-root user
USER nodejs

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${port}${healthPath} || exit 1

# Environment
ENV NODE_ENV=production
ENV PORT=${port}

EXPOSE ${port}

CMD ["node", "${entryPoint}"]
`;
}
