// ═══════════════════════════════════════════════════════════════════
// Docker Image (Dockerfile) Template
// Dynamically generates stages based on local dependencies
// 
// Supports two modes:
// 1. Base image (core-base) - builds shared dependencies once
// 2. Service images - extend from base for fast builds
// 
// Compatible with both:
// - Local file: dependencies (development)
// - Published npm/GitHub packages (production)
// ═══════════════════════════════════════════════════════════════════

import type { DockerConfig, LocalDependency } from '../types.js';

// Default to latest Node.js LTS
const DEFAULT_NODE_VERSION = '24';

/**
 * Generate Dockerfile for core-base image
 * This builds access-engine and core-service once, to be reused by all services
 * 
 * When packages are published to npm/GitHub, this base image becomes optional -
 * services can install them directly via npm ci
 */
export function generateCoreBaseDockerfile(nodeVersion = DEFAULT_NODE_VERSION): string {
  return `# ═══════════════════════════════════════════════════════════════════
# Core Base Image - Shared dependencies for all microservices
# Generated by core-service infra generator
# 
# BUILD FROM PROJECT ROOT:
#   docker build -f Dockerfile.core-base -t core-base:latest .
# 
# This image contains pre-built:
#   - access-engine
#   - core-service
# 
# NOTE: When packages are published to npm/GitHub, services can install
# them directly via npm ci, making this base image optional.
# ═══════════════════════════════════════════════════════════════════

# Stage 1: Build access-engine
FROM node:${nodeVersion}-alpine AS access-engine-builder
WORKDIR /build/access-engine
COPY access-engine/package*.json ./
RUN npm ci --ignore-scripts
COPY access-engine/src ./src
COPY access-engine/tsconfig.json ./
RUN npm run build
# Remove dev dependencies to reduce size
RUN npm prune --production

# Stage 2: Build core-service
FROM node:${nodeVersion}-alpine AS core-service-builder
WORKDIR /build/core-service
COPY --from=access-engine-builder /build/access-engine /build/access-engine
COPY core-service/package*.json ./
RUN npm ci --ignore-scripts
COPY core-service/src ./src
COPY core-service/tsconfig.json ./
RUN npm run build
# Remove dev dependencies to reduce size
RUN npm prune --production

# Stage 3: Final base image with built packages (minimal)
FROM node:${nodeVersion}-alpine AS core-base
WORKDIR /packages

# Copy built packages (ready to be used by services)
COPY --from=access-engine-builder /build/access-engine ./access-engine
COPY --from=core-service-builder /build/core-service ./core-service

# Label for identification
LABEL org.opencontainers.image.title="core-base"
LABEL org.opencontainers.image.description="Pre-built shared dependencies for microservices"
`;
}

/**
 * Generate Dockerfile for a service that extends from core-base
 * Much faster since core dependencies are pre-built
 * 
 * NPM/GitHub Compatibility:
 * - When core-service and access-engine are published to npm/GitHub,
 *   they will be installed via npm ci automatically
 * - The core-base image becomes optional (for faster local dev builds)
 * - The service can detect published packages via absence of file: in package.json
 */
export function generateServiceDockerfile(config: DockerConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    nodeVersion = DEFAULT_NODE_VERSION,
    entryPoint = 'dist/index.js',
    localDependencies = [],
  } = config;
  
  const appFolder = name;
  
  // Separate core deps (from base image) and other local deps
  const coreDeps = ['access-engine', 'core-service'];
  const hasLocalCoreDeps = localDependencies.some(d => coreDeps.includes(d.name));
  const otherLocalDeps = localDependencies.filter(d => !coreDeps.includes(d.name));
  
  // Generate stages for non-core local dependencies (like shared-validators)
  const otherDepsStages = otherLocalDeps.map((dep, idx) => {
    const dependsOnCore = (dep.dependsOn || []).some(d => coreDeps.includes(d));
    const copyFromBase = dependsOnCore && hasLocalCoreDeps ? `
# Copy core dependencies from base
COPY --from=core-base /packages/access-engine /build/access-engine
COPY --from=core-base /packages/core-service /build/core-service` : '';
    
    return `# Build ${dep.name}
FROM node:${nodeVersion}-alpine AS ${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder
WORKDIR /build/${dep.folderPath}${copyFromBase}
COPY ${dep.folderPath}/package*.json ./
RUN npm ci --ignore-scripts
COPY ${dep.folderPath}/src ./src
COPY ${dep.folderPath}/tsconfig.json ./
RUN npm run build
RUN npm prune --production`;
  }).join('\n\n');
  
  // Copy commands for other local deps
  const copyOtherDeps = otherLocalDeps.map(dep => 
    `COPY --from=${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder /build/${dep.folderPath} /${dep.folderPath}`
  ).join('\n');
  
  const copyOtherDepsToNodeModules = otherLocalDeps.map(dep => 
    `COPY --chown=nodejs:nodejs --from=${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder /build/${dep.folderPath} /app/node_modules/${dep.name}`
  ).join('\n');
  
  const otherDepsStagesSection = otherDepsStages ? `${otherDepsStages}\n\n` : '';
  const copyOtherDepsSection = copyOtherDeps ? `\n${copyOtherDeps}` : '';
  const copyOtherDepsToNodeModulesSection = copyOtherDepsToNodeModules ? `\n${copyOtherDepsToNodeModules}` : '';

  // Core base section - only needed for local file: dependencies
  const coreBaseSection = hasLocalCoreDeps ? `# Use pre-built core dependencies (for local file: deps)
FROM core-base:latest AS core-base

` : `# NOTE: core-service and access-engine are installed via npm ci
# (no core-base image needed when packages are published)

`;

  // Copy core from base - only for local deps
  const copyCoreFromBase = hasLocalCoreDeps ? `
# Copy pre-built core packages from base image
COPY --from=core-base /packages/access-engine /access-engine
COPY --from=core-base /packages/core-service /core-service` : '';

  // Remove symlinks and copy core - only for local deps
  const handleCoreSymlinks = hasLocalCoreDeps ? `
# Remove symlinks created by npm for file: dependencies
RUN rm -f /app/node_modules/access-engine /app/node_modules/core-service

# Copy pre-built packages to node_modules
COPY --chown=nodejs:nodejs --from=core-base /packages/access-engine /app/node_modules/access-engine
COPY --chown=nodejs:nodejs --from=core-base /packages/core-service /app/node_modules/core-service` : '';

  return `# ═══════════════════════════════════════════════════════════════════
# Optimized microservice build - Node ${nodeVersion} LTS Alpine
# Generated by core-service infra generator
# 
${hasLocalCoreDeps ? `# REQUIRES: core-base:latest image (for local file: dependencies)
#   docker build -f Dockerfile.core-base -t core-base:latest .
# ` : `# NOTE: Using published npm packages (no core-base required)
# `}
# BUILD FROM PROJECT ROOT:
#   docker build -f ${appFolder}/Dockerfile -t ${name}:latest .
# ═══════════════════════════════════════════════════════════════════

${coreBaseSection}${otherDepsStagesSection}# Build app
FROM node:${nodeVersion}-alpine AS app-builder
WORKDIR /app
${copyCoreFromBase}${copyOtherDepsSection}

# Copy app package files and install
COPY ${appFolder}/package*.json ./
RUN npm ci --ignore-scripts

# Install TypeScript for build
RUN npm install -D typescript

# Copy source and build
COPY ${appFolder}/src ./src
COPY ${appFolder}/tsconfig.json ./
RUN npx tsc

# Remove dev dependencies to minimize image size
RUN npm prune --production

# Production stage - minimal image
FROM node:${nodeVersion}-alpine AS production
WORKDIR /app

# Security: create non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001

# Copy built files with correct ownership
COPY --chown=nodejs:nodejs --from=app-builder /app/node_modules ./node_modules
COPY --chown=nodejs:nodejs --from=app-builder /app/dist ./dist
COPY --chown=nodejs:nodejs --from=app-builder /app/package.json ./
${handleCoreSymlinks}${copyOtherDepsToNodeModulesSection}

# Switch to non-root user
USER nodejs

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${port}${healthPath} || exit 1

# Environment
ENV NODE_ENV=production
ENV PORT=${port}

EXPOSE ${port}

CMD ["node", "${entryPoint}"]
`;
}

/**
 * Generate a Docker build stage for a local dependency
 */
function generateDependencyStage(
  dep: LocalDependency, 
  nodeVersion: string, 
  allDeps: LocalDependency[]
): string {
  const stageName = `${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder`;
  
  // Find dependencies that need to be copied in
  const copyFromStages = (dep.dependsOn || [])
    .map(depName => {
      const parentDep = allDeps.find(d => d.name === depName);
      if (!parentDep) return '';
      const parentStageName = `${parentDep.name.replace(/[^a-z0-9]/gi, '-')}-builder`;
      return `COPY --from=${parentStageName} /build/${parentDep.folderPath} /build/${parentDep.folderPath}`;
    })
    .filter(Boolean)
    .join('\n');
  
  const copyFromBlock = copyFromStages ? `\n# Copy dependencies\n${copyFromStages}\n` : '';
  
  return `# Build ${dep.name}
FROM node:\${nodeVersion}-alpine AS ${stageName}
WORKDIR /build/${dep.folderPath}
${copyFromBlock}
COPY ${dep.folderPath}/package*.json ./
RUN npm ci --ignore-scripts
COPY ${dep.folderPath}/src ./src
COPY ${dep.folderPath}/tsconfig.json ./
RUN npm run build`;
}

/**
 * Sort dependencies by their dependency order (dependencies first)
 */
function sortDependencies(deps: LocalDependency[]): LocalDependency[] {
  const sorted: LocalDependency[] = [];
  const visited = new Set<string>();
  
  function visit(dep: LocalDependency) {
    if (visited.has(dep.name)) return;
    
    // Visit dependencies first
    for (const depName of dep.dependsOn || []) {
      const parentDep = deps.find(d => d.name === depName);
      if (parentDep) visit(parentDep);
    }
    
    visited.add(dep.name);
    sorted.push(dep);
  }
  
  deps.forEach(visit);
  return sorted;
}

export function generateDockerfile(config: DockerConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    nodeVersion = '20',
    entryPoint = 'dist/index.js',
    localDependencies = [],
  } = config;
  
  const appFolder = name;
  
  // Sort dependencies so dependencies are built before dependents
  const sortedDeps = sortDependencies(localDependencies);
  
  // Generate build stages for each local dependency
  const dependencyStages = sortedDeps.map((dep, idx) => 
    `# Stage ${idx + 1}: Build ${dep.name}
FROM node:${nodeVersion}-alpine AS ${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder
WORKDIR /build/${dep.folderPath}
${(dep.dependsOn || []).map(depName => {
  const parentDep = sortedDeps.find(d => d.name === depName);
  if (!parentDep) return '';
  return `COPY --from=${parentDep.name.replace(/[^a-z0-9]/gi, '-')}-builder /build/${parentDep.folderPath} /build/${parentDep.folderPath}`;
}).filter(Boolean).join('\n')}
COPY ${dep.folderPath}/package*.json ./
RUN npm ci --ignore-scripts
COPY ${dep.folderPath}/src ./src
COPY ${dep.folderPath}/tsconfig.json ./
RUN npm run build`
  ).join('\n\n');
  
  // Generate COPY commands for app-builder stage
  const copyBuiltPackages = sortedDeps.map(dep => 
    `COPY --from=${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder /build/${dep.folderPath} /${dep.folderPath}`
  ).join('\n');
  
  // Generate COPY commands for production stage
  // Copy to node_modules for direct imports (with correct ownership)
  const copyToNodeModules = sortedDeps.map(dep => 
    `COPY --chown=nodejs:nodejs --from=${dep.name.replace(/[^a-z0-9]/gi, '-')}-builder /build/${dep.folderPath} /app/node_modules/${dep.name}`
  ).join('\n');
  
  // Generate command to remove symlinks created by npm for file: dependencies
  const removeSymlinks = sortedDeps.map(dep => 
    `/app/node_modules/${dep.name}`
  ).join(' ');
  
  const appBuilderStageNum = sortedDeps.length + 1;
  const productionStageNum = sortedDeps.length + 2;

  // Handle case with no local dependencies
  if (sortedDeps.length === 0) {
    return `# ═══════════════════════════════════════════════════════════════════
# Multi-stage build for minimal image size
# Generated by core-service infra generator
# 
# BUILD FROM PARENT DIRECTORY:
#   docker build -f ${appFolder}/Dockerfile -t ${name} .
# ═══════════════════════════════════════════════════════════════════

# Stage 1: Build app
FROM node:${nodeVersion}-alpine AS app-builder
WORKDIR /app

# Copy app package files and install
COPY ${appFolder}/package*.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY ${appFolder}/src ./src
COPY ${appFolder}/tsconfig.json ./
RUN npx tsc

# Stage 2: Production
FROM node:${nodeVersion}-alpine AS production
WORKDIR /app

# Security: non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001
USER nodejs

# Copy built files
COPY --from=app-builder --chown=nodejs:nodejs /app/node_modules ./node_modules
COPY --from=app-builder --chown=nodejs:nodejs /app/dist ./dist
COPY --from=app-builder --chown=nodejs:nodejs /app/package.json ./

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${port}${healthPath} || exit 1

# Environment
ENV NODE_ENV=production
ENV PORT=${port}

EXPOSE ${port}

CMD ["node", "${entryPoint}"]
`;
  }

  return `# ═══════════════════════════════════════════════════════════════════
# Multi-stage build for minimal image size
# Generated by core-service infra generator
# 
# BUILD FROM PARENT DIRECTORY:
#   docker build -f ${appFolder}/Dockerfile -t ${name} .
# 
# Local dependencies: ${sortedDeps.map(d => d.name).join(', ')}
# ═══════════════════════════════════════════════════════════════════

${dependencyStages}

# Stage ${appBuilderStageNum}: Build app
FROM node:${nodeVersion}-alpine AS app-builder
WORKDIR /app

# Copy built local packages
${copyBuiltPackages}

# Copy app package files and install
COPY ${appFolder}/package*.json ./
RUN npm ci --ignore-scripts

# Install TypeScript for build
RUN npm install -D typescript

# Copy source and build
COPY ${appFolder}/src ./src
COPY ${appFolder}/tsconfig.json ./
RUN npx tsc

# Stage ${productionStageNum}: Production
FROM node:${nodeVersion}-alpine AS production
WORKDIR /app

# Security: create non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001

# Copy built files with correct ownership (no slow chown needed)
COPY --chown=nodejs:nodejs --from=app-builder /app/node_modules ./node_modules
COPY --chown=nodejs:nodejs --from=app-builder /app/dist ./dist
COPY --chown=nodejs:nodejs --from=app-builder /app/package.json ./

# Remove symlinks created by npm for file: dependencies (they point to build-time paths)
RUN rm -f ${removeSymlinks}

# Copy local packages to node_modules (replacing the removed symlinks)
${copyToNodeModules}

# Switch to non-root user
USER nodejs

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
  CMD wget --no-verbose --tries=1 --spider http://localhost:${port}${healthPath} || exit 1

# Environment
ENV NODE_ENV=production
ENV PORT=${port}

EXPOSE ${port}

CMD ["node", "${entryPoint}"]
`;
}
