// ═══════════════════════════════════════════════════════════════════
// Kubernetes Manifests Template
// ═══════════════════════════════════════════════════════════════════

import type { K8sConfig } from '../types.js';

export function generateK8sManifests(config: K8sConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    namespace = 'default',
    replicas = 3,
    minReplicas = 3,
    maxReplicas = 20,
    cpuRequest = '250m',
    cpuLimit = '500m',
    memoryRequest = '256Mi',
    memoryLimit = '512Mi',
    domain = 'api.your-domain.com',
    secretName = `${name}-secrets`,
    imageRegistry,
    imageName = imageRegistry ? `${imageRegistry}/${name}:latest` : `${name}:latest`
  } = config;

  return [
    generateDeployment(name, namespace, replicas, imageName, port, healthPath, secretName, cpuRequest, cpuLimit, memoryRequest, memoryLimit),
    generateService(name, namespace, port),
    generateIngress(name, namespace, domain),
    generateHPA(name, namespace, minReplicas, maxReplicas),
    generateSecrets(name, namespace, secretName),
  ].join('\n---\n');
}

function generateDeployment(
  name: string,
  namespace: string,
  replicas: number,
  imageName: string,
  port: number,
  healthPath: string,
  secretName: string,
  cpuRequest: string,
  cpuLimit: string,
  memoryRequest: string,
  memoryLimit: string
): string {
  return `# ═══════════════════════════════════════════════════════════════════
# Kubernetes Deployment - ${name}
# Generated by service-core infra generator
# ═══════════════════════════════════════════════════════════════════

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    app: ${name}
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
        - name: ${name}
          image: ${imageName}
          ports:
            - containerPort: ${port}
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "${port}"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ${secretName}
                  key: mongo-uri
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ${secretName}
                  key: redis-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${secretName}
                  key: jwt-secret
          resources:
            requests:
              cpu: "${cpuRequest}"
              memory: "${memoryRequest}"
            limits:
              cpu: "${cpuLimit}"
              memory: "${memoryLimit}"
          livenessProbe:
            httpGet:
              path: ${healthPath}
              port: ${port}
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: ${healthPath}
              port: ${port}
            initialDelaySeconds: 5
            periodSeconds: 10
`;
}

function generateService(name: string, namespace: string, port: number): string {
  return `
# ═══════════════════════════════════════════════════════════════════
# Service (internal load balancing)
# ═══════════════════════════════════════════════════════════════════

apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  selector:
    app: ${name}
  ports:
    - port: 80
      targetPort: ${port}
  type: ClusterIP
`;
}

function generateIngress(name: string, namespace: string, domain: string): string {
  return `
# ═══════════════════════════════════════════════════════════════════
# Ingress (external access with TLS)
# ═══════════════════════════════════════════════════════════════════

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${name}
  namespace: ${namespace}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
    - hosts:
        - ${domain}
      secretName: ${name}-tls
  rules:
    - host: ${domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${name}
                port:
                  number: 80
`;
}

function generateHPA(name: string, namespace: string, minReplicas: number, maxReplicas: number): string {
  return `
# ═══════════════════════════════════════════════════════════════════
# Horizontal Pod Autoscaler
# ═══════════════════════════════════════════════════════════════════

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${name}
  minReplicas: ${minReplicas}
  maxReplicas: ${maxReplicas}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
`;
}

function generateSecrets(name: string, namespace: string, secretName: string): string {
  return `
# ═══════════════════════════════════════════════════════════════════
# Secrets (create with: kubectl create secret generic ${secretName} ...)
# ═══════════════════════════════════════════════════════════════════

apiVersion: v1
kind: Secret
metadata:
  name: ${secretName}
  namespace: ${namespace}
type: Opaque
stringData:
  # Note: Update mongo-uri for your replica set configuration in production
  mongo-uri: "mongodb://mongo:27017/${name.replace(/-/g, '_')}?replicaSet=rs0"
  redis-url: "redis://redis:6379"
  jwt-secret: "shared-jwt-secret-change-in-production"
`;
}

