// ═══════════════════════════════════════════════════════════════════
// Nginx Configuration Template
// ═══════════════════════════════════════════════════════════════════

import type { NginxConfig, MultiServiceNginxConfig, ServiceEndpoint } from '../types.js';

export function generateNginxConf(config: NginxConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    upstreamName = name.replace(/-/g, '_'),
    rateLimit = 100,
    proxyEndpoints = ['/graphql'],
    includeHttps = true
  } = config;

  const locationBlocks = proxyEndpoints.map(endpoint => generateLocationBlock(endpoint, upstreamName)).join('\n');

  let conf = generateMainConfig(upstreamName, name, port, healthPath, rateLimit, locationBlocks);

  if (includeHttps) {
    conf += generateHttpsServerBlock();
  }

  conf += `}
`;

  return conf;
}

function generateLocationBlock(endpoint: string, upstreamName: string): string {
  return `
        # ${endpoint} endpoint
        location ${endpoint} {
            # Rate limiting
            limit_req zone=api_limit burst=50 nodelay;
            limit_conn conn_limit 100;

            # Proxy settings
            proxy_pass http://${upstreamName}${endpoint};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection "";
            
            # Timeouts
            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;

            # Buffer settings
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
        }`;
}

function generateMainConfig(
  upstreamName: string,
  name: string,
  port: number,
  healthPath: string,
  rateLimit: number,
  locationBlocks: string
): string {
  return `# ═══════════════════════════════════════════════════════════════════
# Nginx Load Balancer Configuration
# Generated by service-core infra generator
# ═══════════════════════════════════════════════════════════════════

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

http {
    # ─────────────────────────────────────────────────────────────────
    # Basic Settings
    # ─────────────────────────────────────────────────────────────────
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # Logging
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    'rt=$request_time uct="$upstream_connect_time" '
                    'uht="$upstream_header_time" urt="$upstream_response_time"';
    
    access_log /var/log/nginx/access.log main;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types application/json application/graphql text/plain;

    # ─────────────────────────────────────────────────────────────────
    # Upstream (Load Balancing)
    # ─────────────────────────────────────────────────────────────────
    upstream ${upstreamName} {
        least_conn;
        keepalive 32;
        server ${name}:${port} max_fails=3 fail_timeout=30s;
    }

    # ─────────────────────────────────────────────────────────────────
    # Rate Limiting
    # ─────────────────────────────────────────────────────────────────
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=${rateLimit}r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    # ─────────────────────────────────────────────────────────────────
    # Server Block
    # ─────────────────────────────────────────────────────────────────
    server {
        listen 80;
        listen [::]:80;
        server_name _;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # Health check endpoint (no rate limit)
        location ${healthPath} {
            proxy_pass http://${upstreamName}${healthPath};
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
${locationBlocks}

        # Default
        location / {
            return 404 '{"error": "Not found"}';
            add_header Content-Type application/json;
        }
    }
`;
}

function generateHttpsServerBlock(): string {
  return `
    # ─────────────────────────────────────────────────────────────────
    # HTTPS Server (uncomment when you have certs)
    # ─────────────────────────────────────────────────────────────────
    # server {
    #     listen 443 ssl http2;
    #     server_name your-domain.com;
    #     
    #     ssl_certificate /etc/nginx/certs/fullchain.pem;
    #     ssl_certificate_key /etc/nginx/certs/privkey.pem;
    #     ssl_protocols TLSv1.2 TLSv1.3;
    #     ssl_ciphers HIGH:!aNULL:!MD5;
    #     
    #     # Same location blocks as above...
    # }
`;
}

// ═══════════════════════════════════════════════════════════════════
// Multi-Service Nginx Configuration (Header-Based Routing)
// ═══════════════════════════════════════════════════════════════════

/**
 * Generate nginx config for multi-service gateway routing
 * Routes requests based on X-Target-Service header
 * 
 * Usage:
 * - Client sends: X-Target-Service: auth|payment|bonus|kyc|notification
 * - Nginx routes to appropriate service
 * - Single /graphql endpoint for all services
 */
export function generateMultiServiceNginxConf(config: MultiServiceNginxConfig): string {
  const {
    gateway,
    rateLimit = 100,
    includeHttps = true,
  } = config;

  const { services, defaultService, port = 80 } = gateway;
  const defaultSvc = defaultService || services[0]?.name || 'default';

  // Generate upstreams
  const upstreams = services.map(svc => generateUpstream(svc)).join('\n');

  // Generate service map for header-based routing
  const serviceMap = generateServiceMap(services, defaultSvc);

  // Generate health aggregation (checks all services)
  const healthChecks = services.map(svc => 
    `        set $${svc.name.replace(/-/g, '_')}_health "";`
  ).join('\n');

  let conf = `# ═══════════════════════════════════════════════════════════════════
# Multi-Service Nginx Gateway Configuration
# Generated by core-service infra generator
# 
# Routing: Header-based (X-Target-Service)
# Services: ${services.map(s => s.name).join(', ')}
# Default: ${defaultSvc}
# ═══════════════════════════════════════════════════════════════════

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

http {
    # ─────────────────────────────────────────────────────────────────
    # Basic Settings
    # ─────────────────────────────────────────────────────────────────
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # Logging with service routing info
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" target_service="$http_x_target_service" '
                    'upstream="$upstream_addr" '
                    'rt=$request_time urt="$upstream_response_time"';
    
    access_log /var/log/nginx/access.log main;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types application/json application/graphql text/plain;

    # ─────────────────────────────────────────────────────────────────
    # Upstreams (Service Backends)
    # ─────────────────────────────────────────────────────────────────
${upstreams}

    # ─────────────────────────────────────────────────────────────────
    # Header-Based Service Routing
    # Maps X-Target-Service header to upstream
    # ─────────────────────────────────────────────────────────────────
${serviceMap}

    # ─────────────────────────────────────────────────────────────────
    # Rate Limiting
    # ─────────────────────────────────────────────────────────────────
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=${rateLimit}r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    # ─────────────────────────────────────────────────────────────────
    # Server Block - Unified Gateway
    # ─────────────────────────────────────────────────────────────────
    server {
        listen ${port};
        listen [::]:${port};
        server_name _;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # ─────────────────────────────────────────────────────────────
        # GraphQL Endpoint - Routes by X-Target-Service header
        # ─────────────────────────────────────────────────────────────
        location /graphql {
            # Rate limiting
            limit_req zone=api_limit burst=50 nodelay;
            limit_conn conn_limit 100;

            # Route to target service based on header
            proxy_pass http://$target_upstream/graphql;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Target-Service $http_x_target_service;
            proxy_set_header Connection "";
            
            # Timeouts
            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;

            # Buffer settings
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
        }

        # ─────────────────────────────────────────────────────────────
        # Health Endpoint - Aggregates all services
        # ─────────────────────────────────────────────────────────────
        location /health {
            default_type application/json;
            return 200 '{"status":"healthy","gateway":"nginx","services":${JSON.stringify(services.map(s => s.name))}}';
        }

        # Per-service health (optional direct access)
${services.map(svc => `        location /health/${svc.name} {
            proxy_pass http://${svc.name.replace(/-/g, '_')}${svc.healthPath || '/health'};
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }`).join('\n')}

        # Default
        location / {
            return 404 '{"error": "Not found", "hint": "Use /graphql with X-Target-Service header"}';
            default_type application/json;
        }
    }
`;

  if (includeHttps) {
    conf += generateHttpsServerBlock();
  }

  conf += `}
`;

  return conf;
}

function generateUpstream(service: ServiceEndpoint): string {
  const upstreamName = service.name.replace(/-/g, '_');
  return `    upstream ${upstreamName} {
        least_conn;
        keepalive 32;
        server ${service.host}:${service.port} max_fails=3 fail_timeout=30s;
    }`;
}

function generateServiceMap(services: ServiceEndpoint[], defaultService: string): string {
  const defaultUpstream = defaultService.replace(/-/g, '_');
  const mappings = services.map(svc => 
    `        "${svc.name}" ${svc.name.replace(/-/g, '_')};`
  ).join('\n');

  return `    map $http_x_target_service $target_upstream {
        default ${defaultUpstream};
${mappings}
    }`;
}

