// ═══════════════════════════════════════════════════════════════════
// Nginx Configuration Template
// ═══════════════════════════════════════════════════════════════════

import type { NginxConfig } from '../types.js';

export function generateNginxConf(config: NginxConfig): string {
  const {
    name,
    port = 3000,
    healthPath = '/health',
    upstreamName = name.replace(/-/g, '_'),
    rateLimit = 100,
    proxyEndpoints = ['/graphql'],
    includeHttps = true
  } = config;

  const locationBlocks = proxyEndpoints.map(endpoint => generateLocationBlock(endpoint, upstreamName)).join('\n');

  let conf = generateMainConfig(upstreamName, name, port, healthPath, rateLimit, locationBlocks);

  if (includeHttps) {
    conf += generateHttpsServerBlock();
  }

  conf += `}
`;

  return conf;
}

function generateLocationBlock(endpoint: string, upstreamName: string): string {
  return `
        # ${endpoint} endpoint
        location ${endpoint} {
            # Rate limiting
            limit_req zone=api_limit burst=50 nodelay;
            limit_conn conn_limit 100;

            # Proxy settings
            proxy_pass http://${upstreamName}${endpoint};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection "";
            
            # Timeouts
            proxy_connect_timeout 10s;
            proxy_send_timeout 60s;
            proxy_read_timeout 60s;

            # Buffer settings
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
        }`;
}

function generateMainConfig(
  upstreamName: string,
  name: string,
  port: number,
  healthPath: string,
  rateLimit: number,
  locationBlocks: string
): string {
  return `# ═══════════════════════════════════════════════════════════════════
# Nginx Load Balancer Configuration
# Generated by service-core infra generator
# ═══════════════════════════════════════════════════════════════════

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

http {
    # ─────────────────────────────────────────────────────────────────
    # Basic Settings
    # ─────────────────────────────────────────────────────────────────
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # Logging
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    'rt=$request_time uct="$upstream_connect_time" '
                    'uht="$upstream_header_time" urt="$upstream_response_time"';
    
    access_log /var/log/nginx/access.log main;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types application/json application/graphql text/plain;

    # ─────────────────────────────────────────────────────────────────
    # Upstream (Load Balancing)
    # ─────────────────────────────────────────────────────────────────
    upstream ${upstreamName} {
        least_conn;
        keepalive 32;
        server ${name}:${port} max_fails=3 fail_timeout=30s;
    }

    # ─────────────────────────────────────────────────────────────────
    # Rate Limiting
    # ─────────────────────────────────────────────────────────────────
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=${rateLimit}r/s;
    limit_conn_zone $binary_remote_addr zone=conn_limit:10m;

    # ─────────────────────────────────────────────────────────────────
    # Server Block
    # ─────────────────────────────────────────────────────────────────
    server {
        listen 80;
        listen [::]:80;
        server_name _;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;

        # Health check endpoint (no rate limit)
        location ${healthPath} {
            proxy_pass http://${upstreamName}${healthPath};
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
${locationBlocks}

        # Default
        location / {
            return 404 '{"error": "Not found"}';
            add_header Content-Type application/json;
        }
    }
`;
}

function generateHttpsServerBlock(): string {
  return `
    # ─────────────────────────────────────────────────────────────────
    # HTTPS Server (uncomment when you have certs)
    # ─────────────────────────────────────────────────────────────────
    # server {
    #     listen 443 ssl http2;
    #     server_name your-domain.com;
    #     
    #     ssl_certificate /etc/nginx/certs/fullchain.pem;
    #     ssl_certificate_key /etc/nginx/certs/privkey.pem;
    #     ssl_protocols TLSv1.2 TLSv1.3;
    #     ssl_ciphers HIGH:!aNULL:!MD5;
    #     
    #     # Same location blocks as above...
    # }
`;
}

